<?php
$page_title='Service FAQs — URDigital Tech';
$page_description='Search detailed answers for every URDigital Tech service, including websites, hosting, marketing, design, consulting, project support, recruiting, data, writing, legal documentation, accounting and tax preparation.';
$services=require 'data.php';
include 'includes/header.php';
?>
<header class="page-hero split-page-hero faq-hero"><div class="hero-orb orb-one"></div><div class="container split-hero-grid"><div class="split-hero-copy reveal"><div class="eyebrow">Service knowledge center</div><h1>Clear answers for every service.</h1><p class="lead">Search by keyword or browse a specific service to understand scope, timing, inputs, collaboration, revisions, and delivery before your project begins.</p><div class="cta-row"><a class="btn btn-primary" href="contact.php">Ask a question →</a><a class="btn btn-ghost" href="schedule.php">Book a call ↗</a></div></div><div class="split-hero-media reveal"><img src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=82" alt="Team reviewing project questions and documentation"><div class="hero-media-badge"><strong><?= count($services) ?></strong><span>service categories</span></div></div></div></header>
<section class="faq-page"><div class="container"><div class="faq-tools reveal"><label class="faq-search"><span>⌕</span><input id="faq-search" type="search" placeholder="Search web design, pricing, revisions, hosting, tax preparation..." aria-label="Search all service FAQs"></label><div class="faq-categories"><button class="active" data-faq-category="all">All services</button><?php foreach($services as $slug=>$service): ?><button data-faq-category="<?= htmlspecialchars($slug) ?>"><?= htmlspecialchars($service['title']) ?></button><?php endforeach; ?></div></div><div id="faq-results"><?php foreach($services as $slug=>$service): ?><section class="faq-group" data-faq-group="<?= htmlspecialchars($slug) ?>"><div class="faq-group-intro"><div><div class="eyebrow"><?= htmlspecialchars($service['title']) ?></div><h2><?= htmlspecialchars($service['title']) ?> FAQs</h2><p><?= htmlspecialchars($service['description']) ?></p></div><a class="text-link" href="<?= htmlspecialchars($slug) ?>.php">View service →</a></div><div class="accordion"><?php foreach($service['faqs'] as $f): ?><details class="reveal faq-item" data-faq-text="<?= htmlspecialchars(strtolower($service['title'].' '.$f['q'].' '.$f['a'])) ?>"><summary><?= htmlspecialchars($f['q']) ?></summary><p><?= htmlspecialchars($f['a']) ?></p></details><?php endforeach; ?></div></section><?php endforeach; ?></div><p class="faq-empty" hidden>No matching questions found. Try another service or keyword.</p></div></section>
<section class="cta-section primary-cta-section"><div class="container"><div class="cta-panel primary-cta-panel reveal"><div><span class="eyebrow">Need a specific answer?</span><h2>Talk through your exact requirements.</h2><p>Share your goals, systems, timeline, and constraints. We will recommend the clearest next step.</p><div class="cta-row"><a href="contact.php" class="btn btn-primary">Send your question →</a><a href="schedule.php" class="btn btn-ghost">Schedule a call ↗</a></div></div><div class="cta-logo">?</div></div></div></section>
<?php include 'includes/footer.php'; ?>
