<?php return [
['name'=>'John Wood','date'=>'6 months ago','text'=>'URDigital Tech helped simplify a few areas that needed clarity. John explained things clearly, focused on practical improvements, and avoided overcomplicating the process. The guidance felt useful and easy to apply.'],
['name'=>'Geraldo Metko','date'=>'6 months ago','text'=>'URDigital Tech helped clean up a few areas that were slowing things down. Patricia was responsive, easy to talk to, and kept the conversation focused on practical improvements.'],
['name'=>'Christopher Mekker','date'=>'5 months ago','text'=>'They are on the cutting edge of AI integration with business communication systems, including office reception, scheduling and CRM.'],
['name'=>'Junk Guys','date'=>'6 months ago','text'=>'URDigital Tech helped simplify a few areas that were unclear before. John was direct, practical, and focused on real solutions instead of fluff.'],
['name'=>'Yousef Rassas','date'=>'a year ago','text'=>'URDigital created a website for me that helped stand out from competitors. Their design process was efficient and effective, delivering an end product that stunned me.'],
['name'=>'Mitchell','date'=>'a year ago','text'=>'Our redesigned site is user-friendly and mobile-optimized, and the SEO improvements have delivered impressive results.'],
['name'=>'Garrett Richter','date'=>'a year ago','text'=>'The new design is sleek, professional, and intuitive. Their SEO strategies have already brought in more organic traffic.'],
['name'=>'Thea Alva','date'=>'a year ago','text'=>'They crafted a tailored digital marketing plan and the ads are getting great results. My customer base and leads are growing.'],
['name'=>'Tao Jung','date'=>'a year ago','text'=>'The website and SEO results have been impressive, with a noticeable boost in traffic, engagement, and mobile usability.'],
['name'=>'Greg Yigit','date'=>'a year ago','text'=>'The team handled our complete website redesign from start to finish. The site looks modern, performs better, and is producing impact.'],
['name'=>'Scott F. White','date'=>'a year ago','text'=>'Their detailed SEO approach improved our rankings and traffic within weeks. Communication was excellent throughout.'],
['name'=>'Kawaii','date'=>'a year ago','text'=>'The new website is sleek, modern, and much more user-friendly. Their SEO expertise has made a huge difference.'],
['name'=>'Pete Rodriguez','date'=>'a year ago','text'=>'They revamped our social media strategy and created consistent, engaging content. Followers and engagement increased significantly.'],
['name'=>'Madison Reed','date'=>'a year ago','text'=>'Their Shopify automation streamlined inventory and order management, saving substantial time and making the store more efficient.'],
['name'=>'Matthew Marsh','date'=>'a year ago','text'=>'URDigital’s expertise in web development and SEO is unmatched. Our website looks fantastic and traffic has improved significantly.'],
['name'=>'Jerome Parker','date'=>'6 months ago','text'=>'They brought clarity and structure to areas that needed it, with practical guidance and a smooth overall experience.'],
['name'=>'Support Team','date'=>'a year ago','text'=>'Amazing team. They handled everything from web design to digital marketing, and the results have been impressive.'],
['name'=>'Ivana Babin','date'=>'a year ago','text'=>'URDigital’s team took care of everything for us. Our business has grown faster than we imagined thanks to their digital expertise.'],
['name'=>'John Shehu','date'=>'a year ago','text'=>'So glad we partnered with URDigital. They revamped our website and boosted our SEO. Excellent work.'],
['name'=>'Alona Didkovska','date'=>'a year ago','text'=>'Their digital marketing strategies brought more leads and visibility to my business.'],
['name'=>'David Nicol','date'=>'a year ago','text'=>'Their social media management boosted my online presence, followers, and engagement.'],
['name'=>'Coaching Service1','date'=>'a year ago','text'=>'Amazing work and service!']
];
